### ISSUE TITLE
Mismatch in number of representative genomes in GTDB-tk data

### ISSUE THREAD

**Issue by jacodela** [Ecogenomics/GTDBTk#101]
Hi,

I noticed that the number of accessions that are labeled as representative in the `GTDB` metadata tables and phylogenetic trees (a total of 28941: 27372 Bacteria + 1569 Archaea) does not match the number of genomes included in the `GTDB-tk` data (22440 in total). The missing 6501 genomes have, on average, high completeness and low contamination (according to the metadata); if this is not the reason, why were they omitted?

**Comment by pchaumeil** [comment]
Hello,
In order to reduce the computational demands. The GTDB-Tk reference tree is a pruned version of the GTDB reference tree where we only keep one reference genome per species name.  In this case, 6501 genomes have been removed because another genome in the GTDB tree would have and better quality and the same species name.

Thanks,
PIerre

**Comment by jacodela** [comment]
Thanks for your quick response and for the useful tool.
