### ISSUE TITLE
gtdbtk - Dependency pplacer 

### ISSUE THREAD

**Issue by jbholm** [Ecogenomics/GTDBTk#115]
Greetings, 

Have you been able to run GTDBTK on Mac OSX Mojave (10.14.4)? I cannot complete a GTDBTK run for any workflow solely because I cannot get pplacer to work. The most recent available binary for Mac is for Darwin, and as such has Darwin-specific requirements. Specifically the error is:

dyld: Library not loaded: /usr/local/lib/libgsl.0.dylib
  Referenced from: /usr/local/bin/pplacer/pplacer
  Reason: image not found
Abort trap: 6

I've requested Mojave binaries via the pplacer website, but I am also asking GTDBTK folks if they have somehow gotten pplacer to work for GTDBTK otherwise.

Thanks!

**Comment by aaronmussig** [comment]
Hello,

I can confirm that it's possible, a previous version of GTDBTk was successfully running on an old Mojave laptop. It's been a while since I've used it but I believe I had success by installing pplacer through [bioconda](https://anaconda.org/bioconda/pplacer) `conda install -c bioconda pplacer `. You may wish to try that.

Thanks.

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
