### ISSUE TITLE
relative evolutionary divergence (RED) meaning

### ISSUE THREAD

**Issue by ucassee** [Ecogenomics/GTDBTk#152]
Hi developer，
      I want to learn more about relative evolutionary divergence (RED) including how it is calculated and what it is based on?  Could you please give me more information? 
      Thanks in advance

**Comment by dparks1134** [comment]
We discuss RED in the GTDB manuscript:
https://www.ncbi.nlm.nih.gov/pubmed/30148503

**Comment by ucassee** [comment]
I find some red value of my bins are 0.33. But those bins are annotated in phylum level in gtdb. I want to know whether  such a low red value  can indicate these bins  belong to new phylum.

**Comment by pchaumeil** [comment]
Following GTDB-Tk rules those bins are in the phylum Marinisomatota because their RED values (0.35) bring the RED value of p__Marinisomatota (0.385) closer to median phylum-level RED value ( 0.345).

You bins will become the most basal members of Marinisomatota.

To verify if your bins are part of a new phylum, You would need to generate a de novo bootstrapped tree and look at the support of the decorated nodes for the Marinisomatota branch.

**Comment by ucassee** [comment]
@pchaumeil Thanks for your reply. 
So do you mean if the RED values below the median phylum-level RED value ( 0.345),  these bins are likely to be a new phlyum ?

**Comment by pchaumeil** [comment]
_So do you mean if the RED values below the median phylum-level RED value ( 0.345), these bins are likely to be a new phylum ?_
It will depends on the branch the bins are on. 
If your bins have a RED values of 0.33 and are placed on the parent branch of p__Marinisomatota (0.385) . They will still be considered as p__Marinisomatota  because they are bringing the RED value of p__Marinisomatota closer to median phylum-level RED value ( 0.345).
But if your bins have a RED values of 0.33 and are placed on the parent branch of p__Patescibacteria(0.341),They will be considered as a new phylum because, otherwise, they would bring the RED value of p__Patescibacteria farther to median phylum-level RED value ( 0.345).

GTDB-Tk doesn't generate bootstrapped trees. So, you will have to get the MSA generated from GTDB=Tk and generate the bootstrapped tree with your preferred phylogenetic tree construction software.

**Comment by ucassee** [comment]
Hi @pchaumeil . 
The `gtdbtk.bac120.msa.fasta` file contains 23470 sequences. Should I use all of them to generate the bootstrapped tree?

**Comment by pchaumeil** [comment]
For a potential new phylum, we would recommend using the full MSA. As a pre-screening, you could pick one representative per order ( or family) to create a bootstrapped tree.

To make sure genomes are part of a new phylum , We would create bootstrapped tree using different models and different sets of markers.
You also need to take into consideration other characteristicsfor your bins like completeness,contamination,quality.....

**Comment by ucassee** [comment]
Hi @pchaumeil.  
I got it! Thanks for your patience!

**Comment by pchaumeil** [comment]
No worries, 
good luck with your research!

**Comment by ucassee** [comment]
Hi @pchaumeil ，I want to know the default RED setting when classify genome to different taxonomy. For example the, the ranges of RED to  phylum, class, genus ...
Could you provide me some information about that ?
