### ISSUE TITLE
different taxonomic classifcations

### ISSUE THREAD

**Issue by mstambou** [Ecogenomics/GTDBTk#154]
hello, I have four genomes in with RefSeq IDs: GCF_000185705.2, GCF_000224655.1, GCF_000144975.1 and GCF000205025.1.

I assigned taxonomies using GTDBTK tool, however when I compared it to Metaphlan2 I have two different taxonomical assignments for the following genome pairs:

GCF_000185705.2, GCF_000224655.1 were assigned to the class 'Desulfovibrionia' by GTDBTK while metaphlan2 assigns them to Deltaproteobacteria

and GCF_000144975.1, GCF000205025.1 were assigned to the class 'Gammaproteobacteria' by GTDBTK while metaphlan2 assigns them to Betaproteobacteria. 

I was wondering any particular reason for this difference?

**Comment by dparks1134** [comment]
Hello. GTDB-Tk is based on the GTDB taxonomy (https://gtdb.ecogenomic.org/) while MetaPhlAn is based on the NCBI taxonomy. These two taxonomies do not always agree due to differences in how they circumscribe taxa and potential misclassifications. For example, GCF_000185705.2 is assigned as to the class Desulfovibrionia in the phylum Desulfobacterota_A in GTDB R04-RS89 while it is assigned as a Deltaproteobacteria in the NCBI taxonomy. The GTDB curation team may be able to provide you with additional information regard these exact taxonomic differences if you wish to contact them (https://gtdb.ecogenomic.org/about#5).

**Comment by pchaumeil** [comment]
This ticket has been resolved by the GTDB curation team.
