### ISSUE TITLE
Consider "iqtree -fast" instead of "FastTree"

### ISSUE THREAD

**Issue by tseemann** [Ecogenomics/GTDBTk#179]
http://www.iqtree.org/doc/Command-Reference

```
-fast 
Turn on the fast tree search mode, where IQ-TREE will just construct two starting trees:
maximum parsimony and BIONJ, which are then optimized by nearest neighbor interchange
(NNI). Introduced in version 1.6.
```

Author says it is more accurate for same speed.

**Comment by dparks1134** [comment]
Our evaluation indicated `IQ-Tree -fast` and `FastTree` deviate from `IQ-Tree` to the same extent. In all cases, known challenging taxa were not always inferred to be monophyletic. We have decided to stay with FastTree for now since we are more familiar with its limitations, but will continue to evaluate other options.
