### ISSUE TITLE
How to understand the alphabetic suffix after genus or species name?

### ISSUE THREAD

**Issue by Duannai** [Ecogenomics/GTDBTk#203]
Although I have read the help page [](https://gtdb.ecogenomic.org/faq#genera_and_species_end_with_alpha_suffix)

**Comment by Duannai** [comment]
Sorry for misoperation.

Although I have read the help page [https://gtdb.ecogenomic.org/faq#genera_and_species_end_with_alpha_suffix](url), I am still confused.

For example, the GTDB-taxonomy of one bin was as follows: 


> d__Bacteria | p__Firmicutes_B | c__Desulfitobacteriia | o__Desulfitobacteriales | f__Desulfitobacteriaceae | g__Desulfitobacterium_A | s__

So, the first question is whether genus Desulfitobacterium_A is the same as genus Desulfitobacterium? or genus Desulfitobacterium_A is a branch of genus Desulfitobacterium?

Can I use the properties of genus Desulfitobacterium to infer the properties of genus Desulfitobacterium_A? For example, the morphological and physiological characteristics.

Meanwhile, the above bin only have a GTDB-based taxonomy, but does not have a NVBI-based taxonomy. Therefore, the last question is how to interpret this situation?

Thanks!

Mort

**Comment by dparks1134** [comment]
Hi Mort,

Desulfitobacterium_A is a distinct genus from Desulfitobacterium within the GTDB taxonomy. It has been given the placeholder name Desulfitobacterium_A since the majority of genomes it encompasses have historically been referred to as Desulfitobacterium. However, it is the assertion of the GTDB taxonomy that this should be consider a new genus that will eventually be given a valid genus name.

GTDB-Tk does not work directly with the NCBI taxonomy. You can get a "quick-and-dirty" majority-votes translation to the NCBI taxonomy using the gtdb_to_ncbi_majority_vote.py script:
https://github.com/Ecogenomics/GTDBTk/tree/stable/scripts

This script is not officially supported at this time and any results should be manually inspected.

Cheers,
Donovan

**Comment by Duannai** [comment]
Thank you for your prompt and clear answer!

So I think it's inappropriate to infer the properties of Desulfitobacterium_A by Desulfitobacterium.

**Comment by dparks1134** [comment]
I don't think this is straight forward. An interesting question is what was being considered when these properties were established. Were the researchers considering organisms just from Desulfitobacterium, just from Desulfitobacterium_A, or organisms from both of these GTDB genera? Do these properties still hold given the broader set of genomes now available?

**Comment by phugenholtz** [comment]
You really need to know the phylogenetic context. If the _A genus has been
divided due to rank normalisation but still forms a monophyletic unit with
the type species, then it is much more likely to share common properties
than if it is a polyphyletic group at some distance from the type species.
