### ISSUE TITLE
Missing output file

### ISSUE THREAD

**Issue by fplaza** [Ecogenomics/GTDBTk#214]
Hi,

The file 'gtdbtk.ar122.summary.tsv'  is not systematically created which makes the script 'gtdb_to_ncbi_majority_vote.py' fail.
Could you fix this?

Best.
Florian

**Comment by aaronmussig** [comment]
Hi Florian,

The script was recently updated on the `staging` branch to check for the existence of this file instead of failing as per issue #210. Please try again using the updated file ([gtdb_to_ncbi_majority_vote.py](https://github.com/Ecogenomics/GTDBTk/blob/staging/scripts/gtdb_to_ncbi_majority_vote.py)). If you're still encountering an error after updating the script please include any output to assist with debugging.

Thanks,
Aaron

**Comment by fplaza** [comment]
Thanks.
It works now.
