### ISSUE TITLE
EXCEPTION: PplacerException

### ISSUE THREAD

**Issue by TonyMane** [Ecogenomics/GTDBTk#217]
Greetings, I have just started using gtdb-tk. I first did a test where I ran two whole genomes through the pipeline (CP000866.1, CP000084.1 corresponding to Nitrosopumilus maritimus and Pelagibacter ubique, respectively). The program ran to completion, produced all the expected result files. However, I am finding that I can not get the program to finish or complete when given metagenomic assembled genomes (MAGs). I have tried to run the progam on two MAGs that are of sufficient quality (90% or greater) with low contamination (less than 1%). Both are Gammaproteobacteria (Thioglobus and Thioalkalivibrio). I have attached the input file directory (test_MAGs) and the output files and the output logs (gtdbtk.log). 
[test_MAGs.tar.gz](https://github.com/Ecogenomics/GTDBTk/files/4038703/test_MAGs.tar.gz)

[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/4038708/gtdbtk.log)

any help is useful. thank you

**Comment by aaronmussig** [comment]
Hello,
Thank you for providing your input data and a log. I am inclined to say that this is due to your server not having enough memory to run pplacer as indicated by:
`[2020-01-08 22:52:13] WARNING: pplacer requires ~113 GB of RAM to fully load the bacterial tree into memory. However, 49.28GB was detected.`

However, you ran a genome through which was classified as Pelagibacter ubique? For that to happen the bacterial pplacer tree would have been loaded into memory (~113GB). Was that done on the same server? 

Alternatively, do you have access to more memory? If not, try run it with the `--scratch_dir` flag (which uses pplacer with the mmap flag). You can also try run it on [kbase](https://kbase.us/applist/apps/kb_gtdbtk/run_kb_gtdbtk) (note that the version is 0.3.2).

**Comment by TonyMane** [comment]
Yes, i believe P. ubique an Nitrosopumilus ran to completion. Worked swimmingly. I have attached this result. I don't think this is a memory issue, because this error shows up during this process (with whole genomes), but the program ends up finishing. 

I attached the log here.
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/4038789/gtdbtk.log)

**Comment by TonyMane** [comment]
I used the --scratch_dir,
