### ISSUE TITLE
Relationship between software version and reference data version ?

### ISSUE THREAD

**Issue by duboism** [Ecogenomics/GTDBTk#223]
As I am maintaining our installation of `GTDBTK`, I have a question related to the relationship between a version of the software and a version of the reference data.

Is a specific version of the software able to use several versions of the data or does it need a specific version ?

From what I understand, there is a *minimum* version of the reference data for a given version of the software but a given version of the reference data can be used with several versions.

**Comment by duboism** [comment]
I have dig a bit in the code and if I'm correct the hash of some data is in the code (in file `gtdbtk/config/config.py`). This is used when running `gtdbtk check_install`.

Therefore a version of the software needs a specific version of the reference data (but the opposite is not true). Am I correct ?

**Comment by duboism** [comment]
Any thought ?

**Comment by dparks1134** [comment]
Hi. Yes, a version of the software requires a specific version of reference data which (at least in later versions of GTDB-Tk) is explicitly checked for. Reference data follows the update cycle of the GTDB which is only expected every 6 to 9 months. We generally make lots of minor changes to GTDB-Tk in this timeframe. We do plan to release a new GTDB-Tk version whenever the reference data changes since this makes it clear that new reference data is available and should be used.

**Comment by duboism** [comment]
Thanks a lot for your message, the situation is much more clear.

I don't know if we should close the issue as other might be interested in.
