### ISSUE TITLE
Any idea about reducing the memory requirement ?

### ISSUE THREAD

**Issue by Gu2uMo** [Ecogenomics/GTDBTk#319]
Hello, 
I note that there is a new version (GTDBtk 1.5.0 and GTDB r202)
However, when I try it, the program remind me that ~204 GB memory is needed (step pplacer for bacteria).
For me, it is kind of trouble...
Is there some setting or other ways to reduce it? 

command  I use
```bash
gtdbtk classify_wf --cpus 40 --genome_dir 00_raw -x fa --out_dir 01_GTDBtk_r202 --pplacer_cpus 16
```

log as 
```txt
WARNING: pplacer requires ~204 GB of RAM to fully load the bacterial tree into memory. However, 196.49 GB was detected. This may affect pplacer performance, or fail if there is insufficient swap space.
```

Thanks

**Comment by pchaumeil** [comment]
Hello,
As the reference tree is getting bigger , the memory requirement for pplacer increases too.
We are aware of this issue and are currently testing alternatives to reduce the memory footprint of the pipeline.

In the meantime, the only solution the reduce slightly the memory is to use the `--scrach_dir` flag on Tk.
This flag enables the `--mmap-file` parameters of pplacer; this will, very roughly, perform disk IO instead of using physical memory. Please find the description of mmap-file [here](https://matsen.github.io/pplacer/generated_rst/pplacer.html#memory-usage)

Regards,
Pierre

**Comment by Gu2uMo** [comment]
> Hello,
> As the reference tree is getting bigger , the memory requirement for pplacer increases too.
> We are aware of this issue and are currently testing alternatives to reduce the memory footprint of the pipeline.
> 
> In the meantime, the only solution the reduce slightly the memory is to use the `--scrach_dir` flag on Tk.
> This flag enables the `--mmap-file` parameters of pplacer; this will, very roughly, perform disk IO instead of using physical memory. Please find the description of mmap-file [here](https://matsen.github.io/pplacer/generated_rst/pplacer.html#memory-usage)
> 
> Regards,
> Pierre

Thanks! 
I ignore the parameter at the first...
Sorry.
