### ISSUE TITLE
Markers with multiple hits

### ISSUE THREAD

**Issue by iuliachiciudean** [Ecogenomics/GTDBTk#332]
Hi,
I know this is not an issue of GTDB-Tk _per se_, but I will go ahead and ask:

How worried should I be about the "% of markers with multiple hits" warnings?

I get those warnings tho my MAG's are more than 90/ less than 5, completeness/contamination according to CheckM.

Thank you for considering replaying,

J

**Comment by pchaumeil** [comment]
Hello,
It is not uncommon to have the "% of markers with multiple hits" warning for good quality genomes.
I would not worry too much about it if the percentage is still low (i.e close to 10%, which is the warning threshold).

Note that the markers used by CheckM are different than the ones used in GTDB-Tk so that is why you may have some GTDB-Tk warnings on good quality genomes.

Cheers,
Pierre

**Comment by iuliachiciudean** [comment]
Thank you, Pierre.

Yes, the % is mainly around 10%.
But I have 2 MAG's with 23-24%.
Should I eliminate those for my analysis on the presumption that they are contaminated?

Best regards,
Iulia

**Comment by dparks1134** [comment]
GTDB-Tk uses 120 bacterial or 122 archaeal genes to determine the position of genomes in the reference tree. Duplicates of these genes is likely an indication of contamination in your MAG, but could be due to legitimate gene duplication. CheckM often uses a much larger and more robust set of genes to makes completeness and contamination estimates. So, ultimate, it is a judgement call and depends on if these MAGs are important for your study. If they aren't critical, it is safer to filter them out from consideration. If they are critical, more work is probably required to establish if they can be trusted.

**Comment by iuliachiciudean** [comment]
Hi guys,

Thank you very much for your replays.
It is really helpful since I am a newbie in metagenomics.
Got it.

Best regards,
Iulia
