### ISSUE TITLE
Could the bacterial tree and archaeal tree be combined to one tree?

### ISSUE THREAD

**Issue by chen318liang** [Ecogenomics/GTDBTk#345]
Could the bacterial tree and archaeal tree be combined to one tree? I want to show them in one figure? How can I combined them? Thanks very much!

**Comment by dparks1134** [comment]
Hi. The bacterial and archaeal trees are inferred from different marker genes. We consider the trees to be unrooted as the correct rootings of these trees remains an open area of research. You can artificially combine them by manipulating the Newick files if you are comfortable proposing a rooting.

**Comment by magibc** [comment]
Hello @dparks1134 or anyone,

I'm newbie in trying to construc a phyloseq object with a unique tree from a shotgun analysis.

I have used UHGG v2 database and I have obtained two trees: one from archaea and the other for bacteria.

As you pointed out the correct rooting still remains an open area of research (e.g. https://www.nature.com/articles/s41467-019-13443-4).

However, due to that in phyloseq I have to include only one phylogenetic tree, I write you if you could recommend me some software to merge the two unrooted trees. I found the ape R package but I would like to know another options.

Thank you on advance for your hints,

Magí

**Comment by dparks1134** [comment]
Hi Magi,

I don't know any software for easily merging two trees. We use DendroPy in GTDB-Tk which is a nice Python package for working with trees, but can be complicated to get started with. You could manually edit the Newick string representation.

Cheers,
Donovan

**Comment by magibc** [comment]
Hi Donovan,

Thanks for your rapid reply! Thanks for your hints, I will try to edit manually as you suggest me beacause I'm still newbie on Python coding.

Thanks,

David.
