### ISSUE TITLE
Using GTDB-TK for a databas of partial bacterial genome

### ISSUE THREAD

**Issue by mkoohim** [Ecogenomics/GTDBTk#426]
Hello,

I have a database biosynthetic gene cluster (BGCs) from different bacteria. BGCs are clusters of adjacent genes which is part of  whole genome of the bacteria. I used GTDB-TK to make a phylogeny tree for these BGCs but unfortunately as its not whole genome I couldn't get any results and in identify step there was not any marker to match with these BGCs. 
I am wondering if there is any way to use GTDB-TK on these BGCs database? 
Ive attached here one of BGC file:

[seq1.zip](https://github.com/Ecogenomics/GTDBTk/files/9388854/seq1.zip)

**Comment by aaronmussig** [comment]
Hi, unfortunately the genome will need hits to marker genes since GTDB-Tk needs hits to either the 53, or 120 single-copy marker genes (for archaea and bacteria respectively).

You may be able to use the `ani_rep` command of GTDB-Tk to try and find the closest representative genome in ANI space, but note you may need a less-stringent alignment fraction value (this can be set with `--min_af`)

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
