### ISSUE TITLE
explanation of incongruent classifications?

### ISSUE THREAD

**Issue by cheberling** [Ecogenomics/GTDBTk#43]
Why do fastANI and pplacer sometimes give conflicting results?  I have cases where fastANI gives > 99% ANI, but all pplacer results are N/A.  What does that mean?

Also, I have at least one case where we think we have a novel species based on our own fastANI calculations and tree inferences, and gtdbtk seems to agree that it's novel, but it doesn't report as much information as I would like.  gtdbtk reports 'None' for all fastANI and pplacer fields, when I know through my own analyses that its closest relative by fastANI ANI is ~90%.  I assume gtdbtk only reports relatives with > 95% ANI?  I think it may still be useful to report the closest relative even if it is not a same-species relative.

But am I correct in assuming that I may have a novel species with the following line:
ve800_81A6_hybrid_assembly_10Apr2018    d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__    None    None    None    None    None    None    None    None    **taxonomic classification fully defined by topology**      None    None

**Comment by dparks1134** [comment]
Hello. FastANI and pplacer do not always agree on species assignments. For example, pplacer may put a genome on a  branch leading to species A, while the closest species by ANI is species B. Such discrepancies typically occur between closely related species and reflect the difference between a phylogeny inferred from a set of concatenated genes vs the average similarity of homologous genes (i.e. ANI).

You are correct that we only report ANI values >= 95%. We also don't calculate ANI between a genome and all genomes in the reference tree as this is computationally prohibitive. We only calculate ANI when necessary to resolve an exact species relationship.

We are working to improve the documentation. The "None" in this case indicates that no species-specific  information was calculated since based on the placement of your genome in the tree we could infer it was a novel species.

**Comment by dparks1134** [comment]
Version 0.1.3 addresses a bug with reporting "None" when information should have been presented. The documentation has also been expanded to fully explain the output of the classification summary files.

**Comment by cheberling** [comment]
I have upgraded to version 0.1.3 and the aforementioned genome still receives "None" for both ANI and tree placement.  'Classification_method' still states 'taxonomic classification fully defined by topology' for this case (method 2 in the new documentation), but the new documentation for version 0.1.3 seems to imply that this should fall under case 3, where RED values would determine species novelty.  

I am already satisfied that for this particular case I can conclude that I have a novel species, but the format of the results do not seem to agree with what was expected with the new version.

Please inform.

**Comment by dparks1134** [comment]
Can you send me the Newick tree that is produced by GTDB-Tk along with the name of the genome you are concerned about? It may be that the taxonomy of the genome is fully defined by the topology of the tree (e.g., sits above two named species and within a defined genus).

**Comment by cheberling** [comment]
Please see the following link for the tree file:
https://puretechhealth.box.com/s/le6srj0loz737re3oiie51hlsslz5dep

The name of the genome is 've800_81A6_hybrid_assembly_10Apr2018 '

**Comment by dparks1134** [comment]
Hello. Right now we are only reporting ANI values if they are >= 95%. I appreciate that this information would be useful even for lower ANI values so we will aim to do this for the next release.
