### ISSUE TITLE
[Errno 2] No such file or directory: 'output/classify/gtdbtk.bac120.summary.tsv'

### ISSUE THREAD

**Issue by francesco-ricci** [Ecogenomics/GTDBTk#448]
Hello everyone,

I am running gtdbtk classify_wf and getting the following error: MESSAGE: [Errno 2] No such file or directory: 'output/classify/gtdbtk.bac120.summary.tsv'

<img width="1160" alt="Screen Shot 2022-11-07 at 12 13 31" src="https://user-images.githubusercontent.com/54572239/200207156-0829cdd1-02e8-4368-9459-ad234934c580.png">

**Comment by pchaumeil** [comment]
Hello,
GDTB-Tk seems to crash because none of the 1078 genomes you are submitting have a bacterial or archaeal marker.
Tk is unable to finish the pipeline and does not generate the proper files because all genomes fail the internal GTDB-Tk Quality Control.
We will modify our code to avoid Tk to crash in this situation and we will add more warnings.
In the meantime, I would recommend running CheckM on those genomes to assess their completeness and contamination.
