### ISSUE TITLE
"closest_placement_reference" is missing

### ISSUE THREAD

**Issue by mars188** [Ecogenomics/GTDBTk#464]
Hello, 

I have 40 bacterial MAGs that I used to create a tree with "gtdbtk classify_wf" option. Here is the command I used. 

`gtdbtk classify_wf --genome_dir selected_genomes --extension fa --out_dir gtdb --cpus 24`

GTDB-tk placed most of my MAGs to their respective reference genomes, however, closest_placement_reference is missing for few of my MAGs. How can i find them? Or do I need to run it differently?

Many thanks,

**Comment by pchaumeil** [comment]
Hi,
The field `closest_placement_reference` is filled when the user genome is placed on a terminal branch leading to a representative genome ( this representative genome will be considered the closest reference genome based on the tree topology). 
If the pplacer places the genome 'high' enough in the tree ( above multiple GTDB reference genomes ) GTDB-Tk does not report the  `closest_placement_reference` value.
Hope this helps

**Comment by zwets** [comment]
@pchaumeil what interpretation (if any) could be given to this, and to incongruent placement in general? Does it suggest that the local tree topology may need revision?

I manage an interesting genome collection: 3,300+ isolates from various (cultured bacteria) sequencing projects in East Africa, which (of course!) I ran through GTDB-Tk. Now I'm struggling with what to make of the fact that 58 of my 64 _Enterobacter_A hormaechei_ have incongruent placement.

About half are pplaced at _Enterobacter quasihormaechei_, the other half have no pplacer placement. Of the latter, 6 aren't _hormaechei_ according to KmerFinder, they are _cloacae. Likewise for my six _E cloacae_M_: four have no pplacer placement (and are called _E asburiae_ by KmerFinder). To complete the picture: I also have a cluster of 3 novel _Enterobacter sp._ (by _de_novo_wf_), as well as alleged _E asburiae_ and _E soli_  that fall outside GTDB ANI radii.

Are these discrepancies due to us sequencing strains that haven't (much) been seen before, or is this just the general (phylo)genomic messiness of the enterobacteriaceae?

**Comment by zwets** [comment]
Maybe this :point_up: should move to the forum?
