### ISSUE TITLE
Is it possible to download the single-copy orthologs for a given clade? How?

### ISSUE THREAD

**Issue by FilipeMatteoli** [Ecogenomics/GTDBTk#521]
Sorry if my question is naive, I've downloaded and used GTDB-tk to classify my set of genomes according to phylum successfully. 

Now, I would like to know which sequences GTDB-tk used for this phylum tree, and for each class subtree. How can I retrieve this set of protein sequences?

**Comment by pchaumeil** [comment]
Hello,
You can find the MSA used for the backbone tree under `<output>/classify/intermediate_results/` and the individual MSA used for each of the individual subtree under `<output>/classify/intermediate_results/pplacer/<tree_number>` (named `user_msa_file.fasta`).
Make sure you use the `--keep_intermediates` flag when running your GTDB-Tk command otherwise all this data will be deleted.

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
