### ISSUE TITLE
ERROR: Failed to parse taxonomy file on line 1 [2023-06-15 23:22:45] ERROR: Not a tab-separated line

### ISSUE THREAD

**Issue by arijitnus** [Ecogenomics/GTDBTk#524]
Hi, I am running gtdbtk denovo_wf on my Metagenome Assembled Genomes (MAGs) and seems it can't read the taxonomy file from classify_wf. May I seek your opinion on this matter? 

I have uploaded the log file and the output classification file

## Server information
- CPU: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
- RAM: 131980808 kB

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/11767430/gtdbtk.log)
[classification_file.xlsx](https://github.com/Ecogenomics/GTDBTk/files/11767445/classification_file.xlsx)

**Comment by pchaumeil** [comment]
Hi,

If you want to read directly the summary files from classify_wf you need to use `--gtdbtk_classification_file` instead of  `--custom_taxonomy_file`  ( although you will have to delete every row where classification is not 7 rank long -i.e all Unclassified Bacteria-)

`--custom_taxonomy_file` only works with the format **GENOME_ID<TAB>d__;p__;c__;o__;f__;g__;s__<ENDOFLINE>**, it only has 2 columns.

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
