### ISSUE TITLE
Differences in annotation results between versions

### ISSUE THREAD

**Issue by wanxn518** [Ecogenomics/GTDBTk#534]
Hello great developer, thanks for your tool, it has helped me immensely with my research, but I'm having a bit of a problem, can you help me out?

I have 87 MAGs in my research and they have inconsistent annotation results at the class level using gtdbtk-v1.7.0 and gtdbtk-v2.3.0 respectively, is this due to a database update? Which result should I trust?

Best,

Xiaonan

**Comment by pchaumeil** [comment]
Hello Xiaonan,
That is correct , results will differ from one version of GTDB-Tk to another due to the underlying data ( representative genomes, reference tree for placement...etc). This data change with each release of GTDB.
We always recommend using the latest GTDB reference database ( which is linked to the latest GTDB-Tk release).
