### ISSUE TITLE
hmmsearch error

### ISSUE THREAD

**Issue by alienzj** [Ecogenomics/GTDBTk#547]
![image](https://github.com/Ecogenomics/GTDBTk/assets/8847420/f53b5567-be01-4e83-b0d2-9119293b8581)

**Comment by pchaumeil** [comment]
Hello,
Apologies for the late reply. 

hmmer has now a design limit of 100K residues for protein sequences. Generally a protein sequence length shouldnt exceed few thousands residues. 
since version 3.3.1 , hmmer is now stopping when the length is greater than 100K ( please see release note [here](https://github.com/EddyRivasLab/hmmer/blob/master/release-notes/RELEASE-3.3.1.md)). We understand it is a problem in our pipeline and will modify the code to catch the error without crashing the full workflow.

In the meantime, I would recommend removing this genome from the analysis.

**Comment by alienzj** [comment]
Hello, thanks!
Based on your suggestion, I removed this genome, and GTDBtk run well.
