### ISSUE TITLE
relative evolutionary divergence (RED) values and median RED values

### ISSUE THREAD

**Issue by Julboteroc** [Ecogenomics/GTDBTk#568]
Dear GTDBTK developers, thank you very much for creating this incredible tool.

I have a question. I used GTDBTK to classify a genome from the Lactobacillaceae family. My genome could not be classified using ANI, so my result was obtained using RED, which yielded 0.95 as it is shown below:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/julia/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/julia/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Lactobacillaceae;g_Limosilactobacillus;s__ | N/A | N/A | N/A | N/A | N/A | GCF_001434095.1 | 95 | d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Lactobacillaceae;g__Fructilactobacillus;s__Fructilactobacillus   fructivorans | 77.58 | 0.212 | d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Lactobacillaceae;g__Fructilactobacillus;s__ | taxonomic classification defined by topology   and ANI | classification based on placement in   class-level tree | N/A | 95.41 | 11 | 0.95171
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

</body>

</html>

According to the RED dictionary "red_dictionary.tsv", my median RED value for the taxonomy rank genus is 0.92. Based on these two values, Is my genome within the genus Limosilactobacillus because 0.95 is greater than 0.92, or is it outside the genus Limosilactobacillus because it falls within the RED interval for genus?
I understand that similar questions have been asked before, but I'm confused because my result indicates "g__Limosilactobacillus;s__", which means, it could be inside the genus?
Thanks in advance

**Comment by phugenholtz** [comment]
Hi JulianaTk predicts that your sequence is a novel species (because species not assigned in the tax string) in the genus Limosilactobacillus (because the genus is assigned)That’s the easiest way to interpret the output. We always recommend inferring a de novo tree to confirm the Tk result.Bw, PhilSent from my iPhoneOn 26 Jan 2024, at 07:14, Juliana Botero Cardona ***@***.***> wrote:﻿
Dear GTDBTK developers, thank you very much for creating this incredible tool.
I have a question. I used GTDBTK to classify a genome from the Lactobacillaceae family. My genome could not be classified using ANI, so my result was obtained using RED, which yielded 0.95 as it is shown below:






<style>

</style>





d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Lactobacillaceae;g_Limosilactobacillus;s__
N/A
N/A
N/A
N/A
N/A
GCF_001434095.1
95
d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Lactobacillaceae;g__Fructilactobacillus;s__Fructilactobacillus   fructivorans
77.58
0.212
d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Lactobacillaceae;g__Fructilactobacillus;s__
taxonomic classification defined by topology   and ANI
classification based on placement in   class-level tree
N/A
95.41
11
0.95171





According to the RED dictionary "red_dictionary.tsv", my median RED value for the taxonomy rank genus is 0.92. Based on these two values, Is my genome within the genus Limosilactobacillus because 0.95 is greater than 0.92, or is it outside the genus Limosilactobacillus because it falls within the RED interval for genus?
I understand that similar questions have been asked before, but I'm confused because my result indicates "g__Limosilactobacillus;s__", which means, it could be inside the genus?
Thanks in advance

**Comment by Julboteroc** [comment]
Dear @phugenholtz , Thank you very much for your reply. 
In the information provided in summary.txt, it states: "An unassigned species (i.e., s__) indicates that the query genome is either i) placed outside a named genus," which means that the appearance of "g__Limosilactobacillus;s_" does not necessarily mean that it belongs to this genus?

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
