### ISSUE TITLE
GTDB-tk has given confliction results for two genomes using different command

### ISSUE THREAD

**Issue by quliping** [Ecogenomics/GTDBTk#587]
I have two genomes namely 'bin.SY63.6' and 'bin.SY19.18' have confused results. Both of them were identified as "d__Bacteria;p__JADFOP01;c__JADFOP01;o__JADFOP01;f__JADFOP01;g__JADFOP01;s__JADFOP01 sp022562795" by the ANI step of the 'classfy_wf' command. However, when I run the 'identify' and 'align' commands to get the sequences of marker genes of the two genome, these two genomes was identified as archaea and present in the archaeal MSA... It is very strange.  The version of gtdb-tk that I used is v2.3.2. By the way, if I add option '--skip_ani_screen' for the 'classfy_wf' command or just use the 'de_novo_wf' command, these two genomes was identified as archaea 'd__Archaea;p__Thermoplasmatota;c__Thermoplasmata;o__RBG-16-68-12;f__JAJISG01;g__;s__'.

I have already submit this question at the GTDB forum, but I submit it at this github page again because I could not submit the two genomes to the GTDB forum.
[Gneomes.zip](https://github.com/Ecogenomics/GTDBTk/files/15219574/Gneomes.zip)

**Comment by pchaumeil** [comment]
Hello,
We did run bin.SY63.6 and bin.SY19.18 Through CheckM v1 and v2 and we got the following results :

**CheckM v1:**

| Genome | Completeness | Contamination |
| --- | --- | --- |
| bin.SY63.6 | 55.72% | 16.82% |
| bin.SY19.18 | 40.53% | 5.61% |

**CheckM v2:**

| Genome | Completeness | Contamination |
| --- | --- | --- |
| bin.SY63.6 | 63.51% | 6.08% |
| bin.SY19.18 | 53.0% | 6.14% |

With both versions of CheckM these genomes are classified as poor quality genomes and their classifications may be erroneous. We recommend analysing genomes with a completeness >=50% and a quality score ( completeness - 5* contamination ) > 50 .

Because both genomes are incomplete and quite fragmented ( 966 contigs for SY63 and 1013 contigs for SY19) , Their `FastANI` alignment fraction is biased and higher that it should be. This have been fixed in `GTDB-Tk release 2.4.0` by using `skani` instead.

I would disregard the ANI results for this genomes and classify them as Archaea. However, as mentioned previously, I would use the final classification with caution, given the quality of the genomes.

**Comment by quliping** [comment]
Thanks for your kindly reply. It seems that the results of fastANI were indeed problematic. 
Since our sample was collected from deep sea and the qulity of DNA extraction and sequencing was not very good. Therefore the quality of many of our MAGs was not very high, but we still want to retain them because all MAGs are very precious.  I tried the lasted version of gtdbtk (v2.4.0), and both of the two genomes were correctly identified as Archaea. 
Thanks again for your suggestion.
Sincerely,
Liping Qu
