### ISSUE TITLE
GTDB-Tk/2.4.0 - Spirochaetota clustering far from other bacteria from the same phylum

### ISSUE THREAD

**Issue by ValterAlmeida** [Ecogenomics/GTDBTk#598]
Hi everyone,

I was using GTDB-Tk/2.3.2, and after updating to GTDB-Tk/2.4.0, some Spirochaetota bacterial species started clustering far from each other in the phylogenetic tree (shown in dark green in the attached figure). I used the same MAGs, version, and script of IQ-Tree2 (IQ-TREE/2.2.2.2) that I used with GTDB-Tk/2.3.2, when all Spirochaetota clustered together. Could someone help me understand what is happening? I would greatly appreciate any thoughts. Thank you in advance!

Valter

![image](https://github.com/user-attachments/assets/d300fef8-8034-4472-bafb-8111c78d62e2)

**Comment by uqmchuvo** [comment]
Hi Valter, 

Thanks for your request!

This phylum has been stably monophyletic between releases. Therefore, I am surprise to see the instability there. It is hard to say from your tree where is dark green and it looks monophyletic as labeled. Maybe use different colour or colour the branches itself. 
 
It would be helpful if you can send you MAGs so that we can double-check what is happening. Also, could you please provide a tree labelling your MAGs using R214 and R220? What is the average quality of your MAGs? 

Once we have this information, we can provide further insight. 

Thanks!

Masha

**Comment by ValterAlmeida** [comment]
Hi Masha,

Thank you so much for your response.

I apologize for the poor quality of the previous phylogenetic tree figure. Please see the attached new figures. The first was generated using GTDB-Tk/2.3.2 (all Spirochaetota in purple) , and the second using GTDB-Tk/2.4.0 (all Spirochaetota in dark green). All the MAGs are more than 50% complete and less than 5% contaminated. Both trees include exactly the same MAGs, but in the first one, there are additional MAGs that are less than 50% complete or more than 5% contaminated. Could you please let me know how to label the MAGs using R214 and R220?

Thank you once more!

Kind regards,
Valter

![Picture 1](https://github.com/user-attachments/assets/98eb366f-149e-4c15-829d-9b0f1e3a59d2)

![Picture 2](https://github.com/user-attachments/assets/99870ec4-671f-4956-be75-d9e075a14151)

**Comment by uqmchuvo** [comment]
Dear Valter, 

Thanks again for your request and sorry for delay in responding. 
I wonder if this issue is still relevant and you need our assistance?.. 

My understanding is that _Spirochaetota_ was monophyletic in the tree inferred using Tk v. 2.3.2 and split after the addition of low quality MAGs using Tk v. 2.4.0? 

I wonder what existing GTDB taxa represented the green branch in your tree and it looks like it is part of _Bacteroidota_. In GTDB, we don't include genomes with completeness below 50% as they would typically lack most of the markers for phylogenetic reconstruction, i.e. they won't provide enough phylogenetic signal. To assign meaningful (to extent possible) taxonomy for such genomes, you would most probably need to use one or two markers present in these MAGs and infer _de novo_ species trees, and then reconcile it with the rest of genome-based tree. 

Please clarify what do you mean by "Could you please let me know how to label the MAGs using R214 and R220?". Do you mean how to assign the labels on the tree? I am using ARB to visualise the trees but it is not a very popular choice, therefore, you could look into tools such as iTOL where you can supply a file with taxonomic labels to decorate your tree. I am sorry but I am not familiar with other tools. 

Please let me know if we can assist you further with this.

Best wishes, 
Masha

**Comment by ValterAlmeida** [comment]
Thank you for your response, Masha.

I apologise for the unclear explanation. To clarify, the Spirochaetota phylum was initially identified as a monophyletic group in the phylogenetic tree constructed using Tk version 2.3.2. However, when the same MAGs\were analysed with Tk version 2.4.0, the phylum was found to be split into separate clades. All MAGs included in this analysis have a completeness of over 50% and a contamination level below 5%.

Have a great day!

Kind regards,
Valter

**Comment by uqmchuvo** [comment]
Hi Valter, 

Thank you for reporting this again! 
It is concerning me and it would be helpful for us to look more into this, and see why this happens.  Would it be possible for your to share the MAGs which you were trying to classify? 
This will help us to troubleshoot the issue. 

Thanks a lot!
Masha

**Comment by ValterAlmeida** [comment]
Hi Masha,

Sure! Could you please send me an email at V.Almeida@massey.ac.nz or share your email address with me? Then I can provide you with a link to download the MAGs.

Thank you for your help again! :)

Kind regards,
Valter
